# Generated by Django 2.2 on 2019-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Contenido', models.TextField()),
                ('Fecha_Creacion', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('Publico_Privado', models.CharField(choices=[('pub', 'publico'), ('pri', 'privado')], default='pub', max_length=3)),
                ('Foto', models.ImageField(default='SOMETHING', upload_to='postPhotos')),
            ],
        ),
    ]
